server:
  port: 10003
spring:
  resources:
    static-locations: classpath:/static/,classpath:/META-INF/resources/
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
  mvc:
    async:
      request-timeout: -1
