server:
  port: 11111
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    password: 123456
    username: root
  redis:
    host: localhost
    port: 6379
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        min-idle: 2
        max-idle: 8
        max-wait: -1

