server:
  port: 10004
spring:
  application:
    name: CRUD
  datasource:
    url: jdbc:mysql://localhost:3306/clouddb01?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      minimum-idle: 4
      maximum-pool-size: 8
